// Auto-generated by fragment_preprocessor.js
// Do not edit this file directly.

import { LightFragment } from "./fragments/light_fragment.js";
import { StaticMeshFragment } from "./fragments/static_mesh_fragment.js";
import { TextFragment } from "./fragments/text_fragment.js";
import { TransformFragment } from "./fragments/transform_fragment.js";
import { UserInterfaceFragment } from "./fragments/user_interface_fragment.js";
import { VisibilityFragment } from "./fragments/visibility_fragment.js";

/**
 * A consolidated collection of all known Fragment classes in the project
 * that might require GPU buffer initialization.
 */
export const ALL_FRAGMENT_CLASSES = [
  LightFragment,
  StaticMeshFragment,
  TextFragment,
  TransformFragment,
  UserInterfaceFragment,
  VisibilityFragment,
];
